version: '3.8'

services:

# GERENCIADOR DE CONTAINERS (DESCOMENTE CASO QUEIRA USAR)
#   portainer:
#     image: portainer/portainer-ce:latest
#     container_name: portainer
#     restart: always
#     ports:
#       - "8000:8000"
#       - "9443:9443"
#     volumes:
#       - /var/run/docker.sock:/var/run/docker.sock
#       - portainer_data:/data

# BANCO DE DADOS (MYSQL)
  database:
    image: mysql
    container_name: mysql-composed
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: R@fa5607123456
    ports:
      - "33060:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

# BACK-END (SPRING-BOOT - EM TESTE)
  # api:
  #   build: 
  #     context: ./sistemadetroca-api
  #     dockerfile: Dockerfile
  #   container_name: api-spring
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     database:
  #       condition: service_healthy

volumes:
  portainer_data:
