version: '3.8'

services:
  # BANCO DE DADOS (MYSQL)
  db:
    image: mysql:8.4
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: R@fa5607123456
      MYSQL_DATABASE: SistemaDeTroca
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 3s
      timeout: 5s
      retries: 5
    networks:
      - sistema_de_troca_net

  # MANAGER
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      db:
        condition: service_healthy
    networks:
      - sistema_de_troca_net

# BACK-END (SPRING-BOOT - EM TESTE)
  backend:
    build:
      context: ./spring-api
      dockerfile: Dockerfile
    container_name: spring-api
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/SistemaDeTroca?createDatabaseIfNotExist=true
    depends_on:
      db:
        condition: service_healthy
    networks:
      - sistema_de_troca_net

networks:
  sistema_de_troca_net: